version: "3.7"

services:
  app:
    image: ghcr.io/wedontpanic/jotoba:latest
    restart: always
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./html:/app/html
      - ./resources:/app/resources
      - ./data:/app/data
